//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.java
//  @ Date : 26.02.2018
//  @ Author : 
//
//




public class Jamnik extends Pies {
	public String nazwa;
	public int wiek;
	public void getNazwa(String nazwa) {

	}
	
	public void getWiek(int wiek) {
	
	}
	
	public void Jamnik(String nazwa, int wiek) {
	
	}
}
