//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.java
//  @ Date : 26.02.2018
//  @ Author : 
//
//




public class Pies extends Ssak {
	public String rasa;
}
