//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.java
//  @ Date : 26.02.2018
//  @ Author : 
//
//




public class Ssak extends Zwierze {
	public Object nazwa;
}
