//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Zwierze.java
//  @ Date : 26.02.2018
//  @ Author : 
//
//




public class Zwierze {
	public String nazwa;
	public String gatunek;
}
